<option value="" selected>--- Chọn Quận/Huyện ---</option>
<option value="25">Ba Đình</option>
<option value="56">Ba Vì </option>
<option value="57">Cầu Giấy </option>
<option value="58">Chương Mỹ </option>
<option value="59">Đan Phượng </option>
<option value="60">Đông Anh </option>
<option value="28">Đống Đa</option>
<option value="61">Gia Lâm </option>
<option value="62">Hà Đông </option>
<option value="27">Hai Bà Trưng</option>
<option value="63">Hoài Đức </option>
<option value="81">Hoàn Kiếm</option>
<option value="64">Hoàng Mai </option>
<option value="65">Long Biên </option>
<option value="66">Mê Linh </option>
<option value="67">Mỹ Đức </option>
<option value="68">Phú Xuyên </option>
<option value="69">Phúc Thọ </option>
<option value="70">Quốc Oai </option>
<option value="71">Sóc Sơn </option>
<option value="72">Sơn Tây </option>
<option value="29">Tây Hồ</option>
<option value="73">Thạch Thất </option>
<option value="74">Thanh Oai </option>
<option value="75">Thanh Trì </option>
<option value="76">Thanh Xuân </option>
<option value="77">Thường Tín </option>
<option value="78">Từ Liêm </option>
<option value="79">Ứng Hòa </option>
